In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
csv_file = "Resources/Food_Supply_kcal_Data.csv"
food_supply_df = pd.read_csv(csv_file)
food_df= food_supply_df[food_supply_df.columns[:-8]].set_index('Country')
food_df

,Alcoholic Beverages,Animal Products,Animal fats,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,Milk - Excluding Butter,...,Pulses,Spices,Starchy Roots,Stimulants,Sugar Crops,Sugar & Sweeteners,Treenuts,Vegetal Products,Vegetable Oils,Vegetables
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0.0000,4.7774,0.8504,0.0,37.1186,0.1501,0.0000,1.4757,1.2006,2.4512,...,0.5003,0.1001,0.3252,0.0750,0.0000,2.2261,0.1251,45.2476,2.3012,0.7504
Albania,0.9120,16.0930,1.0591,0.0,16.2107,0.8091,0.1471,3.8982,3.8688,9.9441,...,0.8091,0.0000,1.2651,0.2501,0.0000,3.4422,0.3972,33.9070,2.8244,2.7508
Algeria,0.0896,6.0326,0.1941,0.0,25.0112,0.4181,0.1195,3.1805,1.2543,3.9869,...,1.0900,0.1195,1.9262,0.1493,0.0000,3.9869,0.2240,43.9749,5.7638,2.0457
Angola,1.9388,4.6927,0.2644,0.0,18.3521,0.0441,0.8372,2.3133,2.9302,0.5067,...,1.4981,0.0000,12.6239,0.0441,0.0000,2.7539,0.0000,45.3184,4.2741,0.3525
Antigua and Barbuda,2.3041,15.3672,1.5429,0.0,13.7215,0.2057,1.7280,3.6824,7.0356,4.6904,...,0.4526,0.3497,0.8434,0.4937,0.0000,5.8218,0.0823,34.6225,4.6904,1.2960
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela (Bolivarian Republic of),0.8454,7.2303,0.6007,0.0,21.3126,0.2892,0.4449,2.3804,3.1368,2.6474,...,0.7341,0.0000,1.3571,0.0667,0.0000,7.7864,0.0000,42.7586,7.5417,0.6674
Vietnam,0.7150,10.9806,0.9363,0.0,26.9833,0.2894,1.0385,1.8046,7.8311,0.5618,...,0.4597,0.4256,0.7150,0.1021,0.1532,2.0940,0.3575,39.0364,1.3279,1.9578
Yemen,0.0000,3.4667,0.3394,0.0,32.0727,0.1455,0.1697,1.1879,2.0121,0.6545,...,1.2121,0.0485,0.3152,0.1212,0.0000,7.0303,0.0242,46.5455,3.9515,0.3636
Zambia,1.1925,3.3043,0.3230,0.0,31.5528,0.1988,0.5714,0.2236,1.5155,0.5217,...,0.2981,0.0745,4.0994,0.0248,0.0000,2.5590,0.0000,46.7081,3.0062,0.4472
Zimbabwe,1.4269,3.9356,0.6904,0.0,29.8044,0.1381,0.1611,0.4373,1.7491,1.0817,...,0.6214,0.0460,1.2888,0.0460,0.0000,5.0403,0.1151,46.0759,6.2601,0.2532

In [49]:
covid_df= food_supply_df[["Country","Confirmed", "Deaths","Recovered", "Active", "Population"]].set_index("Country")
covid_df

,Confirmed,Deaths,Recovered,Active,Population
Country,,,,,
Afghanistan,0.120684,0.004680,0.095114,0.019903,38928000.0
Albania,1.399542,0.029563,0.701621,0.668358,2838000.0
Algeria,0.191816,0.005555,0.123971,0.062290,44357000.0
Angola,0.047103,0.001079,0.025026,0.020998,32522000.0
Antigua and Barbuda,0.146939,0.004082,0.135714,0.007143,98000.0
...,...,...,...,...,...
Venezuela (Bolivarian Republic of),0.359808,0.003159,0.342224,0.014425,28645000.0
Vietnam,0.001412,0.000036,0.001248,0.000127,96209000.0
Yemen,0.007433,0.002082,0.005090,0.000262,29826000.0
Zambia,0.096279,0.001942,0.092940,0.001398,18384000.0
Zimbabwe,0.068149,0.001864,0.058151,0.008134,14863000.0

In [5]:
grains= food_supply_df[["Cereals - Excluding Beer", "Oilcrops", "Spices"]].sum(axis=1)
grains

0      37.3938
1      17.2993
2      25.3995
3      19.4316
4      14.6678
        ...
165    21.3571
166    29.2986
167    32.2909
168    34.8074
169    30.5408
Length: 170, dtype: float64

In [6]:
vegs=food_supply_df[["Pulses", "Starchy Roots", "Sugar Crops", "Vegetal Products", "Vegetables"]].sum(axis=1)
vegs

0      46.8235
1      38.7320
2      49.0368
3      59.7929
4      37.2145
        ...
165    45.5172
166    42.3221
167    48.4364
168    51.5528
169    48.2393
Length: 170, dtype: float64

In [7]:
fruits=food_supply_df[["Fruits - Excluding Wine", "Treenuts"]].sum(axis=1)
fruits

0      1.6008
1      4.2954
2      3.4045
3      2.3133
4      3.7647
        ...
165    2.3804
166    2.1621
167    1.2121
168    0.2236
169    0.5524
Length: 170, dtype: float64

In [8]:
protein=food_supply_df[["Animal Products", "Animal fats", "Aquatic Products, Other", "Meat", "Milk - Excluding Butter", "Offals", "Eggs", "Fish, Seafood"]].sum(axis=1)
protein

0       9.5548
1      32.1860
2      12.0652
3       9.3855
4      30.7344
        ...
165    14.4828
166    21.9441
167     6.9091
168     6.5838
169     7.8481
Length: 170, dtype: float64

In [9]:
misc=food_supply_df[["Miscellaneous", "Stimulants", "Sugar & Sweeteners", "Vegetable Oils", "Alcoholic Beverages"]].sum(axis=1)
misc

0       4.6273
1       7.4875
2      10.0941
3       9.0770
4      13.6186
        ...
165    16.2624
166     4.2730
167    11.1515
168     6.8322
169    12.8193
Length: 170, dtype: float64

In [10]:
clean_food=pd.DataFrame({'Grains': grains, 'Vegetables':vegs, 'Fruits':fruits, 'Proteins':protein, "Misc":misc})
clean_food

      Grains  Vegetables  Fruits  Proteins     Misc
0    37.3938     46.8235  1.6008    9.5548   4.6273
1    17.2993     38.7320  4.2954   32.1860   7.4875
2    25.3995     49.0368  3.4045   12.0652  10.0941
3    19.4316     59.7929  2.3133    9.3855   9.0770
4    14.6678     37.2145  3.7647   30.7344  13.6186
..       ...         ...     ...       ...      ...
165  21.3571     45.5172  2.3804   14.4828  16.2624
166  29.2986     42.3221  2.1621   21.9441   4.2730
167  32.2909     48.4364  1.2121    6.9091  11.1515
168  34.8074     51.5528  0.2236    6.5838   6.8322
169  30.5408     48.2393  0.5524    7.8481  12.8193

[170 rows x 5 columns]

In [11]:
country= food_supply_df[['Country']]
clean_food_df= country.join(clean_food).set_index("Country")
clean_food_df

,Grains,Vegetables,Fruits,Proteins,Misc
Country,,,,,
Afghanistan,37.3938,46.8235,1.6008,9.5548,4.6273
Albania,17.2993,38.7320,4.2954,32.1860,7.4875
Algeria,25.3995,49.0368,3.4045,12.0652,10.0941
Angola,19.4316,59.7929,2.3133,9.3855,9.0770
Antigua and Barbuda,14.6678,37.2145,3.7647,30.7344,13.6186
...,...,...,...,...,...
Venezuela (Bolivarian Republic of),21.3571,45.5172,2.3804,14.4828,16.2624
Vietnam,29.2986,42.3221,2.1621,21.9441,4.2730
Yemen,32.2909,48.4364,1.2121,6.9091,11.1515
Zambia,34.8074,51.5528,0.2236,6.5838,6.8322
Zimbabwe,30.5408,48.2393,0.5524,7.8481,12.8193

In [12]:
clean_food_df["Total"]= clean_food_df.sum(axis=1)
clean_food_df

,Grains,Vegetables,Fruits,Proteins,Misc,Total
Country,,,,,,
Afghanistan,37.3938,46.8235,1.6008,9.5548,4.6273,100.0002
Albania,17.2993,38.7320,4.2954,32.1860,7.4875,100.0002
Algeria,25.3995,49.0368,3.4045,12.0652,10.0941,100.0001
Angola,19.4316,59.7929,2.3133,9.3855,9.0770,100.0003
Antigua and Barbuda,14.6678,37.2145,3.7647,30.7344,13.6186,100.0000
...,...,...,...,...,...,...
Venezuela (Bolivarian Republic of),21.3571,45.5172,2.3804,14.4828,16.2624,99.9999
Vietnam,29.2986,42.3221,2.1621,21.9441,4.2730,99.9999
Yemen,32.2909,48.4364,1.2121,6.9091,11.1515,100.0000
Zambia,34.8074,51.5528,0.2236,6.5838,6.8322,99.9998
Zimbabwe,30.5408,48.2393,0.5524,7.8481,12.8193,99.9999

In [13]:
#double check numbers
food_df.sum(axis=1)

Country
Afghanistan                           100.0002
Albania                               100.0002
Algeria                               100.0001
Angola                                100.0003
Antigua and Barbuda                   100.0000
                                        ...
Venezuela (Bolivarian Republic of)     99.9999
Vietnam                                99.9999
Yemen                                 100.0000
Zambia                                 99.9998
Zimbabwe                               99.9999
Length: 170, dtype: float64

In [53]:
#Merge food and covid df
food_covid_df= pd.merge(clean_food_df, covid_df, on= "Country", how= "inner")
food_covid_df

,Grains,Vegetables,Fruits,Proteins,Misc,Total,Confirmed,Deaths,Recovered,Active,Population
Country,,,,,,,,,,,
Afghanistan,37.3938,46.8235,1.6008,9.5548,4.6273,100.0002,0.120684,0.004680,0.095114,0.019903,38928000.0
Albania,17.2993,38.7320,4.2954,32.1860,7.4875,100.0002,1.399542,0.029563,0.701621,0.668358,2838000.0
Algeria,25.3995,49.0368,3.4045,12.0652,10.0941,100.0001,0.191816,0.005555,0.123971,0.062290,44357000.0
Angola,19.4316,59.7929,2.3133,9.3855,9.0770,100.0003,0.047103,0.001079,0.025026,0.020998,32522000.0
Antigua and Barbuda,14.6678,37.2145,3.7647,30.7344,13.6186,100.0000,0.146939,0.004082,0.135714,0.007143,98000.0
...,...,...,...,...,...,...,...,...,...,...,...
Venezuela (Bolivarian Republic of),21.3571,45.5172,2.3804,14.4828,16.2624,99.9999,0.359808,0.003159,0.342224,0.014425,28645000.0
Vietnam,29.2986,42.3221,2.1621,21.9441,4.2730,99.9999,0.001412,0.000036,0.001248,0.000127,96209000.0
Yemen,32.2909,48.4364,1.2121,6.9091,11.1515,100.0000,0.007433,0.002082,0.005090,0.000262,29826000.0
Zambia,34.8074,51.5528,0.2236,6.5838,6.8322,99.9998,0.096279,0.001942,0.092940,0.001398,18384000.0
Zimbabwe,30.5408,48.2393,0.5524,7.8481,12.8193,99.9999,0.068149,0.001864,0.058151,0.008134,14863000.0

In [44]:
#Call next source
csv_file = "Resources/Food_Supply_Quantity_kg_Data .csv"
quantity_food_df = pd.read_csv(csv_file)
quantity_df= quantity_food_df.set_index('Country')
quantity_df

,Alcoholic Beverages,Animal fats,Animal Products,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,Milk - Excluding Butter,...,Vegetables,Vegetal Products,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population,Unit (all except Population)
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0.0014,0.1973,9.4341,0.0000,24.8097,0.2099,0.0350,5.3495,1.2020,7.5828,...,6.7642,40.5645,4.5,29.8,0.120684,0.004680,0.095114,0.019903,38928000.0,%
Albania,1.6719,0.1357,18.7684,0.0000,5.7817,0.5815,0.2126,6.7861,1.8845,15.7213,...,11.7753,31.2304,22.3,6.2,1.399542,0.029563,0.701621,0.668358,2838000.0,%
Algeria,0.2711,0.0282,9.6334,0.0000,13.6816,0.5277,0.2416,6.3801,1.1305,7.6189,...,11.6484,40.3651,26.6,3.9,0.191816,0.005555,0.123971,0.062290,44357000.0,%
Angola,5.8087,0.0560,4.9278,0.0000,9.1085,0.0587,1.7707,6.0005,2.0571,0.8311,...,2.3041,45.0722,6.8,25,0.047103,0.001079,0.025026,0.020998,32522000.0,%
Antigua and Barbuda,3.5764,0.0087,16.6613,0.0000,5.9960,0.2274,4.1489,10.7451,5.6888,6.3663,...,5.4495,33.3233,19.1,NaN,0.146939,0.004082,0.135714,0.007143,98000.0,%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela (Bolivarian Republic of),2.5952,0.0403,14.7565,0.0000,12.9253,0.3389,0.9456,7.6460,3.8328,9.3920,...,4.1474,35.2416,25.2,21.2,0.359808,0.003159,0.342224,0.014425,28645000.0,%
Vietnam,1.4591,0.1640,8.5765,0.0042,16.8740,0.3077,2.6392,5.9029,4.4382,0.6069,...,11.9508,41.4232,2.1,9.3,0.001412,0.000036,0.001248,0.000127,96209000.0,%
Yemen,0.0364,0.0446,5.7874,0.0000,27.2077,0.2579,0.5240,5.1344,2.7871,1.8911,...,3.2135,44.2126,14.1,38.9,0.007433,0.002082,0.005090,0.000262,29826000.0,%
Zambia,5.7360,0.0829,6.0197,0.0000,21.1938,0.3399,1.6924,1.0183,1.8427,1.7570,...,3.4649,43.9789,6.5,46.7,0.096279,0.001942,0.092940,0.001398,18384000.0,%
Zimbabwe,4.0552,0.0755,8.1489,0.0000,22.6240,0.2678,0.5518,2.2000,2.6142,4.4310,...,2.3213,41.8526,12.3,51.3,0.068149,0.001864,0.058151,0.008134,14863000.0,%

In [47]:
clean_quantity_df= clean_quantity_df[["Obesity", "Undernourished", "Confirmed", "Deaths", "Recovered", "Active", "Population"]]
clean_quantity_df

,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population
Country,,,,,,,
Afghanistan,4.5,29.8,0.120684,0.004680,0.095114,0.019903,38928000.0
Albania,22.3,6.2,1.399542,0.029563,0.701621,0.668358,2838000.0
Algeria,26.6,3.9,0.191816,0.005555,0.123971,0.062290,44357000.0
Angola,6.8,25,0.047103,0.001079,0.025026,0.020998,32522000.0
Antigua and Barbuda,19.1,NaN,0.146939,0.004082,0.135714,0.007143,98000.0
...,...,...,...,...,...,...,...
Venezuela (Bolivarian Republic of),25.2,21.2,0.359808,0.003159,0.342224,0.014425,28645000.0
Vietnam,2.1,9.3,0.001412,0.000036,0.001248,0.000127,96209000.0
Yemen,14.1,38.9,0.007433,0.002082,0.005090,0.000262,29826000.0
Zambia,6.5,46.7,0.096279,0.001942,0.092940,0.001398,18384000.0
Zimbabwe,12.3,51.3,0.068149,0.001864,0.058151,0.008134,14863000.0